### PR TITLE
fix: ticket analytics report

### PR DESCRIPTION
**Pull request by NileshPithiya**
fix ticket analytics report, remove filters from report company,project.
change filter name customer to contact.
user able to filter contact wise, ticket type, ticket priority, assignee wise status wise like open,closed, resolved, replied.

Screenshot from 2022-11-28 15-43-56

### CODE REVIEW

**Comment by kamaljohnson** [comment]
@NileshPithiya is this PR work in progress or ready to merge ?

**Comment by NileshPithiya** [comment]
Ready for merge

**Comment by kamaljohnson** [comment]
@NileshPithiya by default the first item in the row is getting selected
image

Instead, it should select all the entries
Like this
image

**Comment by kamaljohnson** [comment]
@NileshPithiya, also by default add the `from` and `to` dates, make the `to` date as `Today` and the `from` date as 1month ago

**Comment by NileshPithiya** [comment]
need to show graph on load? or select only all rows

**Comment by NileshPithiya** [comment]
add default date as per discuss and select all row when report load.
Screenshot from 2022-11-30 18-09-27

**Pull request merged**
