### PR TITLE
feat: Dashboard

### PR DESCRIPTION
**Pull request by esafwan**
Implements dashboard in Frappe Desk with various informational cards & charts.

Frappe Desk (17)

**Charts available:**
- Ticket Summary
- Tickets by Type
- Ticket Trends(Count)
- Customer Satisfaction

**Info Cards:**
- Unresolved/Open/Replied
- Due today
- Avg. First Response
- Avg. Resolution
- Resolution within SLA

### CODE REVIEW

**Comment by fadilsid** [comment]
@kamaljohnson  can you review this PR ?

**Comment by kamaljohnson** [comment]
image

@fadilsid these cards when clicked should redirect to the ticket list view with the filters applied via URL query, ryt ??
@harshit-30 what do you think ?

**Comment by kamaljohnson** [comment]
image

instead of user name, IMO it should be user full name (or first name)

**Comment by kamaljohnson** [comment]
image

by default the date picker should select a range (eg: the current month)

**Comment by kamaljohnson** [comment]
@fadilsid please format the code.
using prettier (using the config in this repo) and also black (the custom one we use) for python.

**Comment by harshit-30** [comment]
> @fadilsid these cards when clicked should redirect to the ticket list view with the filters applied via URL query, ryt ?? @harshit-30 what do you think?

@kamaljohnson We can skip this for now.

**Comment by fadilsid** [comment]
> image
> 
> by default the date picker should select a range (eg: the current month)

@kamaljohnson  fixed in latest commit.

**Comment by fadilsid** [comment]
> image
> 
> instead of user name, IMO it should be user full name (or first name)

fixed [800dc3c](https://github.com/frappe/desk/pull/878/commits/800dc3cb9863183512392590064468375f4405d9)

**Comment by fadilsid** [comment]
> @fadilsid please format the code. using prettier (using the config in this repo) and also black (the custom one we use) for python.

fixed 
[8d23334](https://github.com/frappe/desk/pull/878/commits/8d233343ee18b156dafeca609e7aa91f7c68ad15)  [bb69a05](https://github.com/frappe/desk/pull/878/commits/bb69a0563e7a3b8f12d5cc3bc9631a6a7d278c8c)

**Comment by kamaljohnson** [comment]
image

image

image

image

**Comment by kamaljohnson** [comment]
image

**Pull request merged**
