### PR TITLE
feat: customer management

### PR DESCRIPTION
**Pull request by esafwan**
Implements option to manage customers. 

## Screenshots:
Frappe Desk (6)

Frappe Desk (7)

Frappe Desk (8)

### CODE REVIEW

**Comment by kamaljohnson** [comment]
@esafwan, @fadilsid, When I create a new customer and click to view the full page, it is showing me blank page

https://user-images.githubusercontent.com/22856401/206982402-560b9763-9073-4a0d-a57c-dfc507681e53.mov

**Comment by kamaljohnson** [comment]
image

please remove the filter box from the customer list, it only supports direct filenames.

**Comment by kamaljohnson** [comment]
Fix the preset filter title issue, its showing `All All Tickets`, `All All Contacts` etc..

refer to this draft PR that I created which fixes this (since edit mode is not enabled in this PR) https://github.com/frappe/desk/pull/862

**Comment by fadilsid** [comment]
> @esafwan, @fadilsid, When I create a new customer and click to view the full page, it is showing me a blank page
> Screen.Recording.2022-12-12.at.12.36.49.PM.mov

@kamaljohnson  can you show the console. I'm not getting this issue in my local.

https://user-images.githubusercontent.com/73826691/207514693-f6d1e72c-25dc-4649-b5dd-18bcf1ab8581.mp4

**Comment by kamaljohnson** [comment]
https://github.com/frappe/desk/pull/862/commits/b670db46638ac69511d4f5a8b8cfb6fe9e7132d8

@fadilsid please refer this fix too.

**Comment by kamaljohnson** [comment]
@fadilsid resolve the conflicts too

**Comment by fadilsid** [comment]
@kamaljohnson I've fixed the issues mentioned and merged with latest main branch. please check.

**Comment by fadilsid** [comment]
@kamaljohnson  can you review this PR?

**Comment by kamaljohnson** [comment]
Uploading Screen Recording 2022-12-29 at 12.41.18 PM.mov…

@fadilsid after adding a customer or a ticket, I had to manually refresh the page to see the item added to the list.
can you do a page reload after the item is created?

**Comment by kamaljohnson** [comment]
@fadilsid also the code is not formatted properly too

**Comment by kamaljohnson** [comment]
@fadilsid I tried creating a ticket from the customer view, and it showed me the option to select contacts that did not belong to that customer

IMO it should show the contacts belonging to that customer only
or after creating the ticket, the contact should be moved to the current customer.

@harshit-30 what do you think ?

**Comment by kamaljohnson** [comment]
https://user-images.githubusercontent.com/22856401/209917266-81a622e3-0584-4513-8667-7b52a98255dc.mov

When I try to change the customer name it does not get updated.

**Pull request merged**
